DELETE http://localhost:3001/api/todo/todo
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImRpbm8xYyIsImlkIjoiNjQyMjE4ZTQyMTllMGQyNzZkZjE1MThhIiwiaWF0IjoxNjc5OTU2NTM0LCJleHAiOjE2Nzk5NTcxMzR9.QYnh-cofSuDdeDafU90ddRrBEuenc7_cCmq3rWFKppQ
Content-Type: application/json

{
    "todoID": "642219febff34ef88c665488"
}