POST http://localhost:3001/api/todo/todo
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImRpbm8xYyIsImlkIjoiNjQyMjE4ZTQyMTllMGQyNzZkZjE1MThhIiwiaWF0IjoxNjgwMTI2MzEzLCJleHAiOjE2ODAxMjY5MTN9.P438WFUT7kuAWTu-LRfVqTmZVG7vgJf5mVwjpmekSOM
Content-Type: application/json

{
    "todo": {
        "title": "Taskit Project",
        "description": "I need to create the client side of the Taskit application"
    }
}